AWSTemplateFormatVersion: '2010-09-09'
Description: Basic EC2 instance setup with a security group and SSH access.

Resources:
  # Security Group for the EC2 instance
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allows SSH from anywhere. Change as needed for security.
      VpcId: !Ref DefaultVPC  # Use Default VPC (or you can reference your custom VPC if desired)

  # EC2 Instance
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro  # Free tier eligible. Change as needed.
      KeyName: !Ref KeyName   # SSH key pair to allow login. Must be created beforehand.
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref DefaultSubnet # Default public subnet for the instance
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI (Update this AMI based on your region)
      DisableApiTermination: true  # Enable termination protection
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: false  # Disable deletion of root volume on instance termination
            VolumeSize: 8  # Size of the root volume in GB
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudoyum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          echo "<h1>Hello from EC2 in Custom VPC with Protection Attributes</h1>" > /var/www/html/index.html

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  DefaultVPC:
    Description: The default VPC ID
    Type: 'AWS::EC2::VPC::Id'

  DefaultSubnet:
    Description: The default subnet ID for the instance
    Type: 'AWS::EC2::Subnet::Id'

Outputs:
  InstancePublicIp:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
    Export:
      Name: InstancePublicIp

  InstanceId:
    Description: The instance ID of the EC2 instance
    Value: !Ref MyEC2Instance
